#!/usr/bin/env ruby
# frozen_string_literal: true

# This script generates the IrcCodes enum.  It gets the codes directly from the
# RFCs.
#
# Usage: ruby ./util/gen_irc_codes_enum.rb > ./src/agent_smith/irc/codes.cr

require 'bundler/inline'

gemfile(false) do
  gem 'faraday'
end

require 'erb'

# the RFCs to look for response codes
RFCS = %w[1459 2812].freeze

# base url for the RFC in text format
RFC_BASE_URL = 'https://tools.ietf.org/rfc/rfc%s.txt'.freeze

regexp = /^\s+(\d{3})\s+([A-Z]{3}_[A-Z]+)/ # witchcraft

codes = {}

RFCS.each do |rfc|
  doc = Faraday.get(format(RFC_BASE_URL, rfc)).body

  codes.merge! doc.scan(regexp).map { |x| [x[1], x[0]] }.to_h
end

codes = codes.sort_by { |_, v| v }.to_h
longest = codes.keys.map(&:length).max

puts ERB.new(DATA.read).result(binding).strip

__END__
# This file was generated by $repo_root/util/gen_irc_codes_enum.rb
# <%= Time.now.strftime '%F %T' %>

module AgentSmith
  module IRC
    enum Codes<% codes.each do |k, v| %>
      <%= k %><%= ' ' * (longest - k.length) %> = <%= v.sub(/\A00/, '  ') %><% end %>

      def code_s
        "%03d" % [value]
      end
    end
  end
end
